# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
arr = np.zeros((10))

3. Create a vector with values ranging from 10 to 49

In [6]:
rng = np.arange(10,49)

4. Find the shape of previous array in question 3

In [7]:
rng.shape

(39,)

5. Print the type of the previous array in question 3

In [8]:
rng.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [9]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/softwares/anaconda/anaSetup\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/softwares/anaconda/anaSetup\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/softwares/anaconda/anaSetup\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\

7. Print the dimension of the array in question 3


In [10]:
print(rng.ndim)

1


8. Create a boolean array with all the True values

In [11]:
boolean = np.ones((10),dtype=bool)

9. Create a two dimensional array




In [12]:
twoDim = np.zeros((10,10))
print(twoDim.ndim)

2


10. Create a three dimensional array



In [13]:
threedim = np.zeros((10,10,10))
print(threedim.ndim)

3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:
reverse = np.random.randn((10))
print(reverse)
reverse = np.flip(reverse)
print(reverse)

[ 0.66798943 -0.81220612 -0.2351463   1.13314339 -0.38471396  0.08961301
 -1.26485369 -0.56096347  0.06419366 -0.14212925]
[-0.14212925  0.06419366 -0.56096347 -1.26485369  0.08961301 -0.38471396
  1.13314339 -0.2351463  -0.81220612  0.66798943]


12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
nullVector = np.array([1 if x == 4 else 0 for x in range(10)])
print(nullVector)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [16]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1,2,3,4,5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [18]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [19]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 == arr2
print(arr3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [20]:
odd = np.arange(0,10)
print(odd[odd % 2 != 0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [21]:
odd[odd % 2 != 0] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [22]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [23]:
twoD = np.ones((4,4))
twoD[1:-1,1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [24]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d = np.where(arr2d == 5,12,arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [25]:
arr3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [26]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [27]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [28]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[:,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
rand = np.random.randn((100)).reshape((10,10))
print(f"Minimun Value {np.amin(rand)}")
print(f"Maximum Value {np.amax(rand)}")

Minimun Value -2.9625171909732533
Maximum Value 2.5330435144058514


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common Elements are : {np.intersect1d(a,b)}")

Common Elements are : [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [31]:
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('==================================================')
print(data[names != 'Will'])

[[ 2.0092979  -1.1925348  -0.60468986  0.29668533]
 [-0.66106579 -0.42366276 -0.40262526  0.204488  ]
 [-0.26082961  0.49244218  1.40867125  0.16792073]
 [-0.31150326 -0.99156129 -1.10855834 -0.29432195]
 [ 0.75862789  1.58829516 -1.42553034 -0.47269828]
 [ 0.82554075  1.08317983 -0.0117385  -0.16150029]
 [ 1.10401673 -0.52612099  1.61492141 -0.16570243]]
[[ 2.0092979  -1.1925348  -0.60468986  0.29668533]
 [-0.66106579 -0.42366276 -0.40262526  0.204488  ]
 [-0.31150326 -0.99156129 -1.10855834 -0.29432195]
 [ 0.82554075  1.08317983 -0.0117385  -0.16150029]
 [ 1.10401673 -0.52612099  1.61492141 -0.16570243]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [33]:
print(data)
print('==================================================')
mask = (names != 'Will') & (names!= 'Joe')
print(data[mask])

[[ 2.0092979  -1.1925348  -0.60468986  0.29668533]
 [-0.66106579 -0.42366276 -0.40262526  0.204488  ]
 [-0.26082961  0.49244218  1.40867125  0.16792073]
 [-0.31150326 -0.99156129 -1.10855834 -0.29432195]
 [ 0.75862789  1.58829516 -1.42553034 -0.47269828]
 [ 0.82554075  1.08317983 -0.0117385  -0.16150029]
 [ 1.10401673 -0.52612099  1.61492141 -0.16570243]]
[[ 2.0092979  -1.1925348  -0.60468986  0.29668533]
 [-0.31150326 -0.99156129 -1.10855834 -0.29432195]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 4.99554506  8.1989093   9.35678537]
 [12.19288525  1.47998766  8.68956459]
 [ 6.93135024 13.30018134  3.56269343]
 [11.0952561   4.40486046  3.02544754]
 [11.55440775 13.43131811  4.34457822]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[ 9.07898006  3.27880187  6.3142641   5.19466741]
  [ 2.77428417  1.34144967  3.53148378 15.93608434]]

 [[ 2.57328079 13.18928728  8.0121691   8.45599146]
  [11.45599204 10.14988773 10.75760553  2.65526703]]]


33. Swap axes of the array you created in Question 32

In [36]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[ 9.07898006  3.27880187  6.3142641   5.19466741]
  [ 2.77428417  1.34144967  3.53148378 15.93608434]]

 [[ 2.57328079 13.18928728  8.0121691   8.45599146]
  [11.45599204 10.14988773 10.75760553  2.65526703]]]
Swapped Axes
[[[ 9.07898006  2.57328079]
  [ 2.77428417 11.45599204]]

 [[ 3.27880187 13.18928728]
  [ 1.34144967 10.14988773]]

 [[ 6.3142641   8.0121691 ]
  [ 3.53148378 10.75760553]]

 [[ 5.19466741  8.45599146]
  [15.93608434  2.65526703]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[3 3 3 4 4 4 2 2 3 2]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")


Array 1 : [12.69498477 11.08861947  4.58107016  4.73999048 10.94606829 11.752475
 10.49790682  3.853328    2.46363903 17.67988142]
Array 2 : [17.3455959   5.26270951  5.8361996  17.05735859 14.25434871  7.22983928
  1.40610485  9.14085334  3.16054756  6.06736499]
New Array : [17.3455959  11.08861947  5.8361996  17.05735859 14.25434871 11.752475
 10.49790682  9.14085334  3.16054756 17.67988142]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [39]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [40]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [41]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [43]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())

[  7  16  22  23  25  38  44  55  68  83 101 118 132 147 164 173 188 189
 202 203]
